# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build lynx keyboard'
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lynx_left nice_view_adapter nice_view","lynx_right nice_view_adapter nice_view"]'
